[project]
name = "structured-abstracts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "colpali-engine>=0.3.3",
    "nvitop>=1.3.2",
    "torch>=2.5.1",
]
